version: '3.8' # Or newer, Portainer typically supports recent versions
services:
  codeingest:
      build:
        context: .
#        no_cache: true
      image: codeingest:latest
      ports:
        - "8800:8800" # Expose port 9000 from the container to the host
